# ─── Theme & Basic Info ───────────────────────────────────────────────────────
remote_theme: daattali/beautiful-jekyll@6.0.1
title: "Humanist Science Insights"
description: "Bringing together social sciences, mathematics and artificial intelligence, and neuroscience in search for unconventional sinergies"
author: "Adrián Redondo Fernández"

# ─── Navegación ───────────────────────────────────────────────────────────────
navbar-links:
  Reviews: "/reviews"
  Articles: "/articles"
  Projects: "/projects"
  About Me: "/aboutme"

# ─── Avatar ───────────────────────────────────────────────────────────────────
avatar: "/images/adri.jpeg"
round-avatar: true

# ─── Redes sociales ──────────────────────────────────────────────────────────
social-network-links:
  email: "adrianrefe4@gmail.com"
  linkedin: "adrirefe4"
  github: "adrianrefe4"

# ─── Organizar contenido ──────────────────────────────────────────────────────
collections:
  reviews:
    output: true
    permalink: /reviews/:title/
  articles:
    output: true
    permalink: /articles/:title/

defaults:
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "post"
      comments: true
      social-share: true
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "post"
      comments: true
      social-share: true
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# ─── Apariencia ───────────────────────────────────────────────────────────────
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# ─── Opciones generales ───────────────────────────────────────────────────────
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

url-pretty: "adrirefe4.github.io"
title-on-all-pages: true
excerpt_length: 50
feed_show_excerpt: true
feed_show_tags: true
post_search: true
edit_page_button: true
navbar-var-length: false

date_format: "%B %-d, %Y"
timezone: "Europe/Madrid"
markdown: kramdown
highlighter: rouge
permalink: /:collection/:title/
paginate: 5

kramdown:
  input: GFM

# ─── Exclusiones y plugins ────────────────────────────────────────────────────
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
